### ISSUE TITLE
Super 777

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#11]
## Synopsis

Users of SuperTokens should be able to exchange one supertoken to other supertoken or non-supertoken through one single transaction by sending them to one easy to remember ens address. 

## What we know

- Defi777 contracts as they are are easy to customize and fork.
  - It is using uniswap
- IWrapper777 is possible to implement in SuperToken. (WIP)
  - Have some quick research in eth-magicians/EIPs with regards to related standards.
- User dashboard does have plan to support better experience of user data of both 777 and super agreements.
  - Before it is ready, what we could have is still helper ens domains as thin contract wrappers redirecting/proxying to the full 777 exchange contract (which supports user data). (helper exchange ens? e.g.)
- Current defi777 may have potential sandwich-attack vulnerability. 

## Checklist

- [ ] Legal clarity on can we sponsor this work on gitcoin ( @mdalie )
- [ ] [Create Super777 and Super777Proxy](https://github.com/superfluid-finance/protocol-monorepo/issues/262)
- [ ] User dashboard user data support

## References

- Product spec: https://www.notion.so/superfluidhq/Super-777-DeFi-51653faf338a44d79511478e45049a0e
  - Tech spec (including SC): https://www.notion.so/superfluidhq/Defi-777-Specifications-fe4cdd7f188f43db9877d44b9eb87ca5
