### ISSUE TITLE
More TOGA UI Improvements

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#128]
Following up https://github.com/superfluid-finance/protocol-monorepo/issues/479

## Notes

    - [ ]  Current Bond amount (animated by stream)
    - [ ]  Users can expand by token, showing more solvency information
        - [ ]  [Green] Latest liquidations ← and who did them. Show last 20 or so

- [ ]  PIC Profitability so far (Since last PIC change). Showing it as APY
    
    $Bond/(totalRewards - slashedAmount)/seconds$*secondsInAYear → APY

ACs    

- [ ]  Multi-wallet compatibility (Web3Modal)
- [ ]  [Gnosis-Safe App Compatibility](https://github.com/gnosis/safe-apps-sdk/tree/master/packages/safe-apps-web3modal)
- [ ]  Pull Request [to toga-suit repository](https://github.com/superfluid-finance/toga-suit)
