### ISSUE TITLE
[INFRA] Manage superfluid.finance via route53 system with code

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#135]
As a sysadmin I'd like to leverage route53 native AWS integrations, such as GEO blocking. Let's change the name servers from godaddy to a relevant AWS route53 account.

## TODOs

- [x] Import GoDaddy config in Route53
- [x] Test resolving using new nameservers
- [x] Configure redirections using Apache on de-vmain without SSL
- [ ] Clean up AWS CloudFront/S3/Certificates
- [ ] Setup route53 configuration as code
- [x] Change name servers on godaddy to point to the route53 servers.
- [ ] Educate the new workflow for relevant people who wants to change sub domains going forward.
