### ISSUE TITLE
[INSIGHTS] Protocol Insights

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#17]
Documentation: https://www.notion.so/superfluidhq/PAS-Protocol-Analytics-Service-bc056f9b0259406b9885e82248501f94

# Checklilst

- [ ] build metrics and visualisations of `v1-events-raw`
- [ ] update `v1-card-information` and the visualizations.
  - [ ] integrate error reporting to the alarm
- [ ] create new `v1-liquidation-context`
- [ ] cleanup old indices
- [ ] setup new dashboards
