### ISSUE TITLE
Support Jarvis Custom Stable Coin on Gnosis Chain

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#171]
As a Jarvis in-house developer,  I'd like to issue our stable coin (a custom super token) with permit (EIP-2612) support. Please add that to the latest Super Token logic contract.

## Checlist

- [x] https://github.com/superfluid-finance/protocol-monorepo/issues/577
- [ ] Roll out to mainnet
- [x] ~~https://github.com/superfluid-finance/protocol-monorepo/issues/589~~
- [ ] Support session with Jarvis
