### ISSUE TITLE
MetaTX based Sidechain Experience

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#18]
## Synopsis

[EIP-2771: Secure Protocol for Native Meta Transactions](https://eips.ethereum.org/EIPS/eip-2771) is a state of the art meta transaction proposal where our host contract could benefit from a "Trusted Forwarder" contract to achieve meta transaction support without rebuilding the infrastructure.

Currently Biconomy is supporting this standard.

## Checklist

- [ ]  [EIP-2771 Support in protocol (tested with biconomy)](https://github.com/superfluid-finance/protocol-monorepo/issues/249) 
- [ ] Setup a biconomy operational account.
- [ ] UI/UX design for the meta-tx sidechain experience.
- [ ] User dashboard support.
