### ISSUE TITLE
[ESG] ESG Development Technical Improvement Items

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#222]
For each ESG we develop, we would like to check one technical improvement item. So that after few iterations we have a ESG development process that is robust and high quality.

## TODOs

- [ ] Foundry network-fork based e2e testing.
- [ ] Use SuperfluidFrameworkDeployer for test framework deployment in HH.
- [ ] Echidna-based invariance testing.
- [ ] Integrate with foundry 1.0.0 coverage support.
