### ISSUE TITLE
[SENTINEL] Improving Internal Profitability Estimation Logic & Improve TOGA

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#246]
Currently sentinel liquidation priority logic is naive in a way that it simply liquidates by first-come-first-serve order. We should improve it to take into account profitability. Additionally, timing could also be a factor, since gas price on certain networks can have spikes.
We should also make improvements to TOGA to solve this same category of issues

## TODOs

- [ ] Public discussion thread: https://github.com/superfluid-finance/protocol-monorepo/discussions/1295
- [ ] Surface and prioritise short term Sentinel & TOGA improvements
- [ ] Make code changes to Sentinel
- [ ] Make code changes to TOGA
- [ ] Roll out involving sentinel community
