### ISSUE TITLE
[ETHEREUM-CONTRACTS] Tool to discover versions of deployments

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/superfluid-stories#379]
**As a** key stakeholder for protocol
**I would like to** have a simple UI where I can discover what versions of the protocol and its peripherals have been deployed
**So we can** easily verify that we are conforming to our branching and deployment strategy across networks and environments.

I would suggest to put this either in Console.

### Acceptance criteria
Can discover versions of deployments for:
- [x] Superfluid Protocol Smart contracts #382
  - [x] Show in console https://github.com/superfluid-finance/superfluid-console/issues/186
- [x] Subgraphs #384
- [ ] Peripheral contracts #383
- [ ] Superfluid-hosted Sentinels #385

**Comment by hellwolf** [comment]
Unimplemented:

 Peripheral contracts #383
Superfluid-hosted Sentinels #385

closing
