### ISSUE TITLE
[SUPER-TOKEN] Make Custom Super Token Repo Great Again

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/superfluid-stories#431]
Epic: https://github.com/superfluid-finance/custom-supertokens/issues/29

- [ ] Clear guidance on how to create custom Super Token in docs.
- [ ] Examples of the canonical way.
- [ ] Keep https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Custom-Super-Token up to date.
