### ISSUE TITLE
[INTEGRATION] Aleph Integration

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/superfluid-stories#514]
## Overview
**Integration context:** https://superfluidhq.slack.com/archives/C03PJ9FQ3R6/p1697706504232339

## Point of Contacts

- **Business case:** Amin
- **Solution:** Fran

## Acceptance criteria
 - [ ] See individual tasks
 - [ ] Satisfies entire acceptance criteria
 - [ ] Code is merged & deployed
 - [ ] Code review is approved by at least 2 reviewers
 - [ ] Tested by Elvijs/QA & discovered bugs resolved
 - [ ] Documentation updated
 - [ ] Assignee/opened by merges PR
 - [ ] Automated E2E tests for happy path
 - [ ] Observability of critical user path
 - [ ] Satisfies specifications (TDD & PRD)
 - [ ] Feature is publicly available
 - [ ] Greenlight from stakeholders

## Links/Resources
 * ...

## Readiness criteria
- [ ] Squad
  - [ ] Members
  - [ ] Commander 
- [ ] Overview
  - [ ] PRD, capturing:
    * What: Problem statement
    * How: Hypothesis/solution
    * Why: Priority justification
  - [ ] TDD, capturing the technical solution (HOW)
  - [ ] Distribution plan, if it is a bet: Who are the target users and how do we get the work in their hands?
  - [ ] Validation plan, what are the key assumptions and how can we test them?
  - [ ] Bet
  - [ ] High-level user flows LoFi wireframes
- [ ] Links/Resources
- [ ] Deadline: max bet cycle 6 weeks
- [ ] Acceptance criteria
- [ ] Communication plan
- [ ] Should at least have one linked ticket/issue
- [ ] Schedule stakeholder kick-off

## Stakeholder kick-off agenda
  - [ ] Overview of PRD to answer WHAT (Problem), HOW (Hypothesis) & WHY (Priority)
  - [ ] Overview of Technical Design Document
  - [ ] Overview of Distribution & Validation Plan
  - [ ] Q&A with stakeholders
  - [ ] Determine if we can commit to the bet:
    - [ ] Well-defined enough?
    - [ ] PRD, TDD as well as distribution & validation plans reasonable?
    - [ ] Will this move the needle (TVS or proxy such as #users)?
