### ISSUE TITLE
[EPIC SOLVENCY] set minimum deposit for relevant tokens

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-stories#670]
## What & Why

We expect the probability of spam activity - as seen in 2021/22 - to go up again in the near future.
If not mitigated by setting min deposit this can lead to solvency operating at a loss (or alternatively persistent insolvencies).

A lot of conceptual work was already done, it's now possible to take action.
The last state I'm well familiar with is the [Minimum Deposit Policy](https://github.com/superfluid-finance/protocol-monorepo/wiki/Governance-Process%3A-Minimum-Deposit-Policy).
More progress was made afterwards in the [Solvency Committee](https://www.notion.so/superfluidhq/Solvency-Committee-8b1704f110914dd382ff23125b26780c).

## AC

- [ ] Automation for creating a list of Super Tokens and min deposit values in place
- [ ] List for first update created and manually checked for plausibility
- [ ] Tooling for creating batch gov actions for setting/changing in deposit values in place
- [ ] Review of protocol for possible issues and removal thereof
- [ ] Review of periphery for possible issues and removal thereof
- [ ] gov actions executed
