### ISSUE TITLE
[EPIC] Sentinel with GDA release incl. snapshot support

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-stories#677]
## Why

The GDA was rolled out to all networks (except eth-mainnet) and GDA support was added to the sentinel.
The SF run sentinels were updated to this version.
The point of the solvency system however is to be community run, thus it's important that we provide everything needed for that.

## Acceptance Criteria

- [x] version set to 1.0
- [x] Readme and example .env are up to date (incl. fixing links broken to SF docs update)
- [x] Update from a pre-GDA deployment works (any required extraordinary steps need to be highlighted in the release notes)
- [x] Snapshots for mainnets exist and are used (unless disabled by the user via config)
- [x] Docker image is provided via https://hub.docker.com/r/superfluidfinance/superfluid-sentinel - with correct tags (version string and latest)
- [x] docker-compose files in the repo work
- [x] docker-compose.yml uses pre-built docker image (reason: it's supposed to be suited for resource constrained environments)
- [x] scripts provided in the `scripts` directory work
