### ISSUE TITLE
[RESOLVER] Improved Token Listing Process

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-stories#80]
As a Super Token issuer, I'd like seeing your token listing process more transparent, and also the token list being published to tokenlists.org, so that Super tokens can be integrated with other DeFi products more easily.

## TODOs

- [ ] Implement the tokenlist generation workflow.
- [ ] Implement the new token listing process.
- [ ] Create the token listing review guideline.
- [ ] Use the tokenlist in User Dashboard

## Notes

The process:

- The requester create an issue to `assets` of predefined template "List a New Token".
- (who ? or automated) create a pull request to add token metadata is created with the provided information extracted from the issues.
- Someone from Superfluid do a review of the information, following a guideline
   - Having some automated system to check the input data
- Approve the pull request.
- Merge the pull request.
- Once pull request merged.
  - Assets server is updated.
  - A Token list compatible with https://tokenlists.org/  is updated and uploaded.
  - Triggers a external workflow in protocol-monorepo for a resolver script action.
  - A resolver operator go and confirm the action
- Complete.
